#!/bin/bash

fedora_(){

	# find paprefs / pipewire alternative

	# Vscode

	sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc &&
	cat <<-EOF | sudo tee /etc/yum.repos.d/vscode.repo' >/dev/null
		[code]
		name=Visual Studio Code
		baseurl=https://packages.microsoft.com/yumrepos/vscode
		enabled=1
		gpgcheck=1
		gpgkey=https://packages.microsoft.com/keys/microsoft.asc
	EOF

	dnf check-update

	srtlnk="https://download1.rpmfusion.org"
	free="free/fedora/rpmfusion-free-release"
	nonfree="nonfree/fedora/rpmfusion-nonfree-release"
	sudo dnf install -y "$srtlnk/$free-$(rpm -E %fedora).noarch.rpm"
	sudo dnf install -y "$srtlnk/$nonfree-$(rpm -E %fedora).noarch.rpm"
	sudo dnf upgrade -y

	# Install Third Party Repositories.
	sudo dnf install -y fedora-workstation-repositories

	# Enable the Google Chrome repo:
	sudo dnf config-manager --set-enabled google-chrome

	# copr
	sudo dnf install -y 'dnf-command(copr)'
	for corp in "${extra_repos[@]}"; do
		sudo dnf copr enable "$corp" -y
	done

	sudo dnf install -y "${packages[@]}"

	[ -f  "$HOME"/.local/Fresh_pack_list ] ||
		dnf list installed >"$HOME/.local/Fresh_pack_list"

	sudo flatpak remote-add --if-not-exists flathub \
		https://flathub.org/repo/flathub.flatpakrepo


	flatpaks=(
		com.dropbox.Client
		com.microsoft.Teams
		com.mattermost.Desktop
		us.zoom.Zoom
		com.discordapp.Discord
		org.gnome.gitlab.YaLTeR.VideoTrimmer
		nl.hjdskes.gcolor3
		com.stremio.Stremio
		io.dbeaver.DBeaverCommunity
		io.dbeaver.DBeaverCommunity.Client.mariadb
		org.gimp.GIMP
		org.audacityteam.Audacity
		com.github.xournalpp.xournalpp
		com.spotify.Client
		org.octave.Octave
		com.ulduzsoft.Birdtray
		org.mozilla.Thunderbird
		com.skype.Client
	)

	sudo flatpak install -y "${flatpaks[@]}"

	# Codecs
	sudo dnf install -y gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel
	sudo dnf install -y lame\* --exclude=lame-devel
	sudo dnf group upgrade --with-optional Multimedia -y

	# Virtualization
	# sudo sed -i '/#unix_sock_group = "libvirt"/s/^#//' /etc/libvirt/libvirtd.conf
	sudo usermod -a -G libvirt "$(whoami)"

	# REMOVE
	sudo dnf remove -y gnome-tour gnome-photos gnome-maps gnome-help

	# Teamviewer
	# wget -q "https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm"
	# sudo teamviewer –daemon disable

	chsh $USER -s /usr/bin/zsh
}