#!/bin/bash

fedora_(){

	# find paprefs / pipewire alternative

	# Vscode

	sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc &&
	sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

	dnf check-update
	# sudo dnf install -y code

	# R
	# sudo dnf install -y 'dnf-command(copr)'
	# sudo dnf copr -y enable iucar/cran
	# sudo dnf install -y R-CoprManager

	srtlnk="https://download1.rpmfusion.org"
	free="free/fedora/rpmfusion-free-release"
	nonfree="nonfree/fedora/rpmfusion-nonfree-release"
	sudo dnf install -y "$srtlnk/$free-$(rpm -E %fedora).noarch.rpm"
	sudo dnf install -y "$srtlnk/$nonfree-$(rpm -E %fedora).noarch.rpm"
	sudo dnf upgrade -y

	# Install Third Party Repositories.
	# sudo dnf install fedora-workstation-repositories
	# Enable the Google Chrome repo:
	sudo dnf config-manager --set-enabled google-chrome
	# sudo dnf install -y google-chrome-stable

	# To do: Install VirtualBox guest utils only on guests.
	# To do: Install Nvidia drivers ?

	for corp in $extra_repos; do
		sudo dnf copr enable "$corp" -y
	done

	# TODO change to array
	sudo dnf install -y $packages

	[ -f  "$HOME"/.local/Fresh_pack_list ] ||
		dnf list installed >"$HOME/.local/Fresh_pack_list"

	sudo flatpak remote-add --if-not-exists flathub \
	https://flathub.org/repo/flathub.flatpakrepo


	flatpaks=(
		com.dropbox.Client
		com.microsoft.Teams
		com.mattermost.Desktop
		us.zoom.Zoom
		com.discordapp.Discord
		org.gnome.gitlab.YaLTeR.VideoTrimmer
		nl.hjdskes.gcolor3
		com.stremio.Stremio
		io.dbeaver.DBeaverCommunity
		io.dbeaver.DBeaverCommunity.Client.mariadb
		org.gimp.GIMP
		org.audacityteam.Audacity
		com.github.xournalpp.xournalpp
		com.spotify.Client
		org.octave.Octave
		com.ulduzsoft.Birdtray
		org.mozilla.Thunderbird
		com.skype.Client
	)

	sudo flatpak install -y "${flatpaks[@]}"

	# Codecs
	sudo dnf install gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel
	sudo dnf install lame\* --exclude=lame-devel
	sudo dnf group upgrade --with-optional Multimedia

	# G810
	# sudo dnf copr enable lkiesow/g810-led
	# sudo dnf install g810-led

	# Virtualization
	# sudo dnf install @virtualization
	# sudo sed -i '/#unix_sock_group = "libvirt"/s/^#//' /etc/libvirt/libvirtd.conf
	sudo usermod -a -G libvirt "$(whoami)"

	# REMOVE
	sudo dnf remove -y gnome-tour gnome-photos gnome-maps gnome-help

	# Teamviewer
	# wget -q "https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm"
	# sudo teamviewer –daemon disable

	chsh $USER -s /usr/bin/zsh
}