#!/usr/bin/env bash
# Copyright (C) 2020 Ioannis Spanos

# License: GNU GPLv3
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# set -x

printLists(){
	local list file_loc i ID
	[ -z "$ID" ] && ID=$(. /etc/os-release; echo "$ID")
	# Warning: the function assumes you give at least one proper package list.
	[ "$#" -lt 1 ] && echo 1>&2 "${FUNCNAME[0]} - Missing arguments." && exit 1
	# Prints the content of `.csv` files given as arguments.
	# Checks for local files first.

	for list in "$@"; do
        file_loc=(	"programs/$ID.$list.csv"
                    "programs/$ID/$list.csv"
                    "programs/$file.csv"
                    "$ID.$list.csv"
                    "$ID/$file.csv"
                    "$list.csv"
                )

		for location in "${file_loc[@]}"; do
			[ -r "$location" ] && cat "$location" && echo && break
		done
		[ "$?" -ne 0 ] && curl -Ls "$progs_repo/$ID/$list.csv"
		# ^--^ SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.
	done
}

printLists "$@"
